### ISSUE TITLE
Found this very useful plugin. Anyway to donate?

### ISSUE THREAD

**Issue by Misaka-0x447f** [hetima/DSP_LSTM#1]

**Comment by hetima** [comment]
If you have PayPal, send to hetima@hetima.com
thanks

**Comment by laguy442** [comment]
I agree, you have done an amazing job.  This has saved me so much time.   I will be making a paypal donation.  My only request is to maybe add a button so when I pick an item from the replicator and it shows  me the formula for that item I could jump to your LSTM screen to see if I making the item and where.   Again, great work.

**Comment by laguy442** [comment]
Great addition to the mod by adding a shortcut key to bring up the LSTM window.   Perfect solution.   Thanks much.
