### ISSUE TITLE
[Suggestions] - Show PLS/ILS name in the Global tab as well, and other

### ISSUE THREAD

**Issue by javiersalcedo** [hetima/DSP_LSTM#11]
Hi Hetima

In case you are keeping a "to do" list, I'd like to share a few suggestions

In the LSTM window, the name of Logistic Stations is shown when the "Local" tab is selected, but on the "Global" tab, only the name of the planet and distance is shown. I think that showing the name of the stations in the Global tab as well would be super helpful
My second suggestion is being able to close the LSTM window by pressing the key to close windows ("E" by default), or other key if the player changed the default in the game settings.
A more "cheaty" suggestion would be to be able to edit Logistic Stations settings directly from the LSTM window, like it's name, storage limits, supply/demand orders, transport range, etc

Your mod is fantastic and I'm barely scratching the surface with it (100 hours). Thank you very much for your dedication

**Comment by hetima** [comment]
switch display name and close with E were added in 0.3.6.
