### ISSUE TITLE
Suggestion: Open PLS/ILS window from LSTM window

### ISSUE THREAD

**Issue by shayded-exe** [hetima/DSP_LSTM#12]
It would be really nice if I could open the actual window for my station from the LSTM window so I can adjust its settings without traveling to it.

**Comment by hetima** [comment]
Such a feature will be implemented in the next version (but only stations on the local planet will be covered).

**Comment by hetima** [comment]
added in 0.3.6

**Comment by shayded-exe** [comment]
You're awesome! Thank you for adding so quick. The option for closing with "E" is also very welcome.

Any reason it's restricted to the local planet?

**Comment by hetima** [comment]
> Any reason it's restricted to the local planet?

Because the program code will be more complexed. Also, I don't want to add cheaty features too much.
