### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Valoneu** [hetima/DSP_LSTM#13]
Some window that would show total avaible items by type in just one UI "station" or smthing :) idk how to say it my eng is not best if you dont ill try to give more details

**Comment by Valoneu** [comment]
or some more general stats would be good

**Comment by hetima** [comment]
Like this?
![tes](https://user-images.githubusercontent.com/33700/158722558-7aac042f-2e6f-43d4-ad1d-99fa0a839b0e.jpg)

Also it might be a good to show the total of all each items if no item is specified by filter.

**Comment by hetima** [comment]
I'll also consider how to add a UI to the statistics panel like BetterStats.

**Comment by Valoneu** [comment]
That looks good but you only see one at the time you could do separate ui and it would show items instead of stations, also the ui is kinda small the original one

**Comment by hetima** [comment]
Next version preview

![tes2](https://user-images.githubusercontent.com/33700/159109225-1c564c3b-cbcc-4f7a-bf33-f7099ac296c5.jpg)

**Comment by Valoneu** [comment]
i want to see the raw numbers tho bcs when i play with mods 100% can mean 100,000 or 10,000,000

**Comment by Valoneu** [comment]
but looks good :)

**Comment by Valoneu** [comment]
thanks for update its very good :)
