### ISSUE TITLE
error occurred

### ISSUE THREAD

**Issue by piggykm** [hetima/DSP_LSTM#14]
When I open statistics window, then an error occurred
version 0.5.0
![image](https://user-images.githubusercontent.com/25445890/159233158-e29d6bc8-3c02-4d60-b19f-c358843a67a6.png)

i used this mods

![image](https://user-images.githubusercontent.com/25445890/159233329-510d1bd5-327f-4fba-a234-3be2d542832f.png)
![image](https://user-images.githubusercontent.com/25445890/159233349-dd43ecb8-d14c-4fb0-8a75-caf30f22c9df.png)

**Comment by starfi5h** [comment]
Can confirm, it happens with only LSTM enabled too.

**Comment by hetima** [comment]
I don't know the cause, but try this, which I made a detailed null check.
[LSTM.dll.zip](https://github.com/hetima/DSP_LSTM/files/8315869/LSTM.dll.zip)

**Comment by starfi5h** [comment]
the null checked version solved the issue in my case.

**Comment by piggykm** [comment]
it works for me thank you.
