### ISSUE TITLE
Game error when using DSP Drone Clearing

### ISSUE THREAD

**Issue by Cringely** [hetima/DSP_LSTM#15]
LSTM seems to be throwing an error when I enable the mode DSP Drone Clearing in-game.

![image](https://user-images.githubusercontent.com/759077/164915456-70fe93d7-12b4-42e4-a531-683565efa09c.png)

When I toggle the mod functionality on in game, and the drones start clearing debris the above error pops up. Is this a LSTM issue or a DSP Drone Clearing issue?

This error was happening prior to the recent large patch.

**Comment by hetima** [comment]
Fixed in 0.6.0
thanks!

**Comment by Cringely** [comment]
Thanks so much for your time! Confirmed working :)
