### ISSUE TITLE
Show station name instead of planet name when an item is picked

### ISSUE THREAD

**Issue by MichaelKim0407** [hetima/DSP_LSTM#17]
Right now if I pick an item on the LSTM window, it shows `planet names + range` for each station. But if I have multiple stations demanding the same item on the same planet I can't tell them apart.

I started renaming all ILS after starting to use this mod, and I think showing station names is more helpful in this case. Maybe a config option for people who don't rename ILS?

Or perhaps just display `ILS name + planet name + range` since there is a lot of space in the window. But maybe some people will make very long names, idk.

**Comment by hetima** [comment]
Currently, you can switch between planet name and station name by pressing the tab key.
I'm trying to figure out if there is room for improvement.

**Comment by MichaelKim0407** [comment]
Oh I see. It works.

It wasn't very clear in the README though, so I had no idea this functionality existed. Perhaps at least if you update the description of `switchDisplayModeHotkey` to say what the key does it would be better.

Thanks!
