### ISSUE TITLE
When using with mod BetterStats, some items missing from stat panel

### ISSUE THREAD

**Issue by ljsnogard** [hetima/DSP_LSTM#2]
When using with [mod BetterStats](https://dsp.thunderstore.io/package/brokenmass/BetterStats/1.3.2/),
and when I want to see the full kinds of products in a planet, on the stat panel,
some items cannot been seen in list of the stat panel.

**Comment by hetima** [comment]
I couldn't find the problem but changed the internal design in 2.0.2.
If showButtonInStatisticsWindow is set to false (and restart game), it won't affect stat window.
