### ISSUE TITLE
ILS set to Local Demand / Remote Storage showing as "Supply" in LSTM

### ISSUE THREAD

**Issue by cabadam** [hetima/DSP_LSTM#22]
Please see the attached screenshot.  I've noticed that ILS that are set to Remote Storage are also showing up as "Supply" within the LSTM view which makes it difficult to track down where the supply actually is.

![Screenshot 2023-03-19 101934](https://user-images.githubusercontent.com/11012233/226186012-f20d2b0b-15fe-4a3d-9bc6-4b0191f42c96.png)

**Comment by hetima** [comment]
Added option "Hide Storaged Slot" (default is on) in 0.8.2

thanks.
