### ISSUE TITLE
Updates for the dark fog release (Dec 15)?

### ISSUE THREAD

**Issue by geeksville** [hetima/DSP_LSTM#25]
Hi Hetima,

I absolutely **love** your mod.  In fact it is the only mod I use for DSP and I consider it near indespensible.

The next DSP release supposedly comes out on Dec 15th.  Are you planning on updating the plugin (if needed) when that new build comes out?  I've never written a Unity plugin but I'm a somewhat adequate software engineer and I'm happy to help in any way.  i.e. if you need a prealpha tester or if because of life you don't have time I can try to figure some things out and send in a PR.

Keep being awesome btw.

Kevin

**Comment by geeksville** [comment]
Btw @PhantomGamers I also notice that apparently you are the soure of the dyson sphere lib bindings on
https://nuget.bepinex.dev/packages/DysonSphereProgram.GameLibs?  Are you planning on pushing new bindings when the dec 15 release drops?  If not (and it would be useful for keeping mods working with that release) I can try.

**Comment by PhantomGamers** [comment]
I will indeed.

**Comment by geeksville** [comment]
ok coolbeans - @hetima in case it is useful, I've updated your project so that it (hopefully) builds in a cross platform way (per [this doc](https://docs.bepinex.dev/articles/dev_guide/plugin_tutorial/2_plugin_start.html) with no absolute paths pointing into your install of DSP.  

I also switched to using the bindings from @PhantomGamers on nuget. Because of this change it seems like there are some slight visibility changes by virtue of pulling that lib from nuget (or possibly the newer compiler I used is stricter).  The project file updates for these changes are here https://github.com/hetima/DSP_LSTM/commit/de871193a75d7491aeece5d57c346617a5108181.

This version seems to build and work with my current DSP install (which is under proton/linux btw but should be same on Windows).

I did this partly to learn how to build/run plugins in DSP (alas, I'm new at all this).  If you have time to update LSTM when the dec 15 DSP release drops that would be incredible.  If you don't I'm happy to give it a try.

okay?

(Someday I'd like to add support to your plugin for showing logistics bot stations also - if that happens I'll ping you and send in a PR for your consideration)

**Comment by hetima** [comment]
merged your changes.
thanks

**Comment by PhantomGamers** [comment]
fwiw I made some comments on that commit with suggestions for improvements

**Comment by geeksville** [comment]
Cool beans both of ya'll!  @PhantomGamers alas I'm afk for a couple of days but when I return to my computer on monday I'll apply your changeas as a cleanish PR and send it to @hetima.  Both of ya'll rock and I'm really looking forward to playing DSP again when the next update comes out.

**Comment by hetima** [comment]
merged #27

**Comment by geeksville** [comment]
btw - wow!  you really were fast on making this new dark fog update.  thanks!
