### ISSUE TITLE
[Feature Request] Remote Cluster and Local Cluster allow proliferator

### ISSUE THREAD

**Issue by w-gates** [hetima/DSP_LSTM#28]
When using the Remote Cluster and Local Cluster I am unable to request proliferator with those towers because the proliferator tower is not part of the network. It would be nice to be able to have proliferator requests ignore the Cluster feature.

**Comment by hetima** [comment]
fixed in 0.8.4
thanks

**Comment by w-gates** [comment]
Thank you.
