### ISSUE TITLE
PersonalLogistics button ovelays DspGameSpeed UI

### ISSUE THREAD

**Issue by Vladyslav-Krot** [hetima/DSP_LSTM#3]
I think would be nice to move PersonalLogistics to not overlay  DspGameSpeed UI

![Снимок](https://user-images.githubusercontent.com/25057045/135890996-f6bb185a-e048-461f-ac0e-e2f849bb864d.PNG)

Awesome mod, really like it, thanks for the development

**Comment by hetima** [comment]
that mod is here
https://github.com/mattsemar/dsp-personal-logistics

**Comment by Vladyslav-Krot** [comment]
sorry
