### ISSUE TITLE
Why are my logistics vessels going as far as possible first?

### ISSUE THREAD

**Issue by talbota70** [hetima/DSP_LSTM#5]
Hi there,

Basically title, I noticed my logistics vessels are going as far as possible first (34.1 LY) to get FireIce rather than the gas giant that is in my local system with 40 orbital collectors and plenty of stored FireIce. I tried adjusting the TLDCBalance float values from 1 to 100 and it still happens. (If I'm being honest, I don't even know if it's your mod that is causing this to happen...but it seemed like a good place to start.)

Thanks for your great mod! :)

**Comment by hetima** [comment]
Example case of TLDCBalance:  
transport range of vessels: 2LY  
TLDCDemandMultiplier: 10  
Import from a range of 2LY when storage is over 3,000.  
When storage is less than 3,000, import from a range of 2x10=20LY.  
Therefore, the first three times you set up a new station, the range will be extended.  

If "transport range of vessels" is left at its default value of infinity, TLDCBalance setting will have no effect (infinity is treated as 10,000LY).  
LSTM does not have the ability to prioritize transport from nearby locations like IntelligentTransport mod.

One solution is to make the "transport range of vessels" small enough and set TLConsiderOppositeRange to true to prevent self-serving imports from other stations if you want.  
Or use IntelligentTransport mod (I haven't used it, so I don't know how it works in detail)
