### ISSUE TITLE
Suggestion: Show if ILS has warpers.

### ISSUE THREAD

**Issue by iansmith42** [hetima/DSP_LSTM#7]
Sometimes I am trying to find the source of a product and search through stations looking for ones with ships in them.

It would be helpful if there was a little warper icon next to the 10/10 display to indicate if a station has them.

Great mod, I can't imagine playing without it.

**Comment by hetima** [comment]
added in 0.3.5 but it's an option. To apply it, set `indicatesWarperSign` configuration to `true`
