### ISSUE TITLE
Option to only request remotelly if storage below X%

### ISSUE THREAD

**Issue by alpe12** [hetima/DSP_LSTM#8]
Use case:
I have many stations that receive products via belts and are set to Local Supply and Remote Demand (because sometimes the local production can't keep up).
Currently, as soon as the storage goes below the limit, it makes a remote request. Making the local production halt once it is delivered.

Alternativelly, an option to make TLRemoteDemandDelay work with Local Supply + Remote Demand would work too.

Thanks anyway.
Great mod.

**Comment by hetima** [comment]
> Alternativelly, an option to make TLRemoteDemandDelay work with Local Supply + Remote Demand would work too.

It seems fine to make this the default behavior.

**Comment by hetima** [comment]
in 0.3.5, all remote demands are now affected by `TLRemoteDemandDelay`.

**Comment by alpe12** [comment]
Thanks. 👍
